### ISSUE TITLE
Add jmx_port config. 

### ISSUE THREAD

**Issue by tdixonspin** [eshepelyuk/cmak-operator#36] opened 2021-07-14 09:36 UTC
The CMAK application has the following line:

`val jmxPortResult = fieldExtended[Int]("jmx_port")(json)`

It would be nice to be able to configure the JMX port in the config file. Not every Kafka is exposing JMX on TCP 12345.

**Comment by ievgenii-shepeliuk** [comment] 2021-07-14 09:43
Dear @tdixonspin 

Why did you put this question here ? Please explain

**Comment by tdixonspin** [comment] 2021-07-14 09:45
I honestly wasn't sure where it put like a feature request. I just noticed that I wasn't able to set a custom JMX port, and it looks like CMAK pulls it from the config, but your operator doesn't account for it in the clusterConfigShared schema.

**Comment by ievgenii-shepeliuk** [comment] 2021-07-14 10:27
> I honestly wasn't sure where to put like a feature request. I just noticed that I wasn't able to set a custom JMX port, and it looks like CMAK pulls it from the config, but your operator doesn't account for it in the clusterConfigShared schema.

how do you handle JMX port configuration outside of K8S ? 
What are exact actions, plz report here.

**Comment by tdixonspin** [comment] 2021-07-15 07:48
Nothing specific outside of K8S. Right now we are exposing TCP 7075 for JMX metrics. It looks like CMAK takes the jmx_port object in for this object:

`case class BrokerIdentity(id: Int, host: String, jmxPort: Int, secure: Boolean, nonSecure:Boolean, endpoints: Map[SecurityProtocol, Int]) {
    def endpointsString: String = endpoints.toList.map(tpl => s"${tpl._1.stringId}:${tpl._2}").mkString(",")
  }`

**Comment by eshepelyuk** [comment] 2021-07-20 00:58
Duplicate of https://github.com/eshepelyuk/cmak-operator/issues/13

**Closed by eshepelyuk** 2021-07-20 00:58 UTC

**Comment by tdixonspin** [comment] 2021-07-20 07:47
I don't have any JMX port configurations outside of K8S.
