### ISSUE TITLE
Additional property ui is not allowed

### ISSUE THREAD

**Issue by ohdearaugustin** [eshepelyuk/cmak-operator#26] opened 2021-03-11 19:34 UTC
First off all great work (=

I'm currently trying to debug the connection from cmake-operator to zookeeper.

Version: 1.4.2

First my values config looked like this:
``` 
  21     cmak:
  22       clusters:
  23         - name: "stage"
  24           kafkaVersion: "2.7.0"
  25           curatorConfig:
  26             zkConnect: "stage-zookeeper-client:2181"
```
For debugging I tried to add some extraArgs to the ui like:

``` 
  21     cmak:
  22       clusters:
  23         - name: "stage"
  24           kafkaVersion: "2.7.0"
  25           curatorConfig:
  26             zkConnect: "stage-zookeeper-client:2181"
  27       ui:
  28         extraArgs:
  29           - "-Djavax.net.debug=ssl,handshake"
```

As I try to update the helm chart I get following message:

Helm upgrade failed: values don't meet the specifications of the schema(s) in the following chart(s):\ncmak-operator:\n- cmak: Additional property ui is not allowed

**Comment by eshepelyuk** [comment] 2021-03-11 19:38
1. jfyi, CMAK doesn't support Kafka greater than 2.4.x
1. your values file has incorrect format, plz double check 
  * https://github.com/eshepelyuk/cmak-operator/blob/master/values.yaml
  * https://artifacthub.io/packages/helm/cmak-operator/cmak-operator?modal=values-schema&path=ui

**Comment by eshepelyuk** [comment] 2021-03-11 19:44
Actually [HERE](https://github.com/yahoo/CMAK/issues/803) pplz are telling that 2.6 is supported, even if it's unavailable in UI.

**Comment by eshepelyuk** [comment] 2021-03-11 20:00
Closing, since caused by incorrect configuration.

**Closed** 2021-03-11 20:01 UTC

**Comment by ohdearaugustin** [comment] 2021-03-11 21:13
Thanks a lot. Probably starred to long at the same values again.

Oh thank you for that info with the version.

**Comment by eshepelyuk** [comment] 2021-03-11 21:14
@ohdearaugustin urw !

**Comment by eshepelyuk** [comment] 2021-03-11 21:21
@ohdearaugustin I'd recommend to take a look at https://akhq.io/
maybe it could be more suitable for your needs

**Comment by ohdearaugustin** [comment] 2021-03-11 21:24
@eshepelyuk  That looks great,. Thank you for the hint (=
